spring:
  application:
    name: employee-management-system
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: tiger@data
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  profiles:
    active: prod

server:
  port: 8081

frontend:
  url: ${FRONTEND_URL}
